version: '3.1'

services:
  bt:
    image: mingfunwong/bt:lamp5.6
    restart: always
    volumes:
       - './www:/www/wwwroot'
    ports:
      - '21:21'
      - '80:80'
      - '443:443'
      - '888:888'
      - '3306:3306'
      - '8888:8888'
      - '39000-39050:39000-39050'

